name: Android CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: burrunan/gradle-cache-action@v1
        name: Build with Gradle
        with:
          job-id: android
          arguments: build
      - name: List Files
        run: find .


      - name: Upload mobile debug APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mobile-debug.apk
          path: mobile/build/outputs/apk/debug/mobile-debug.apk

      - name: Upload release (unsigned) mobile APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mobile-release-unsigned.apk
          path: mobile/build/outputs/apk/release/mobile-release-unsigned.apk
          if-no-files-found: warn

      - name: Upload release mobile APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mobile-release.apk
          path: mobile/build/outputs/apk/release/mobile-release.apk
          if-no-files-found: warn

      - name: Upload wear debug APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wear-debug.apk
          path: wear/build/outputs/apk/debug/wear-debug.apk

      - name: Upload release (unsigned) wear APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wear-release-unsigned.apk
          path: wear/build/outputs/apk/release/wear-release-unsigned.apk
          if-no-files-found: warn

      - name: Upload release wear APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wear-release.apk
          path: wear/build/outputs/apk/release/wear-release.apk
          if-no-files-found: warn

      - uses: burrunan/gradle-cache-action@v1
        name: Unit Test
        with:
          job-id: android
          arguments: testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
